### ISSUE TITLE
Flatten wrapper does not work as expected

### ISSUE THREAD

**Issue by twni2016** [proroklab/popgym#19]
Hi authors,

First, thanks for providing a benchmark dedicated for memory-based tasks. I am trying to install and run your benchmark but meet some problems. 

I'd like to use Flatten wrapper in your repo. Following your instructions.
```python
import gymnasium as gym
import popgym
from popgym.wrappers import  Flatten

env_name = ...
env = gym.make(env_name)

Flatten(env) # cause error
```
It raises error of assert error https://github.com/proroklab/popgym/blob/master/popgym/core/wrapper.py#L13, when I use `gym.make` to create an env, but not using`popgym.envs.`.  

Secondly, I think there is a bug in Flatten wrapper: https://github.com/proroklab/popgym/blob/master/popgym/wrappers/flatten.py#L27 this should be on observation_space, not action_space.

Now my workaround is to use `from gymnasium.wrappers import FlattenObservation` instead.

**Comment by smorad** [comment]
Thanks for the report. I think this probably depends on the gymnasium version you are using, as they seem to love making breaking changes.

At this point, I will probably remove the `gym.make` capabilities as this is not the first time `gymnasium` updates have broken this. You can try using categories defined [here](https://github.com/proroklab/popgym/blob/master/popgym/envs/__init__.py) instead of `gym.make`.

e.g.
```python
import popgym
print(popgyms.envs.ALL)
print(popgyms.envs.CONTROL_HARD)

```

**Comment by smorad** [comment]
Closing this as the bug appears to be fixed.
